version: '3'

services:
  postgres:
    image: postgres
    container_name: my-postgres-container
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"

  kafka:
    image: wurstmeister/kafka:latest
    container_name: my-kafka-container
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9093,OUTSIDE://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9093,OUTSIDE://0.0.0.0:9092
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    ports:
      - "9092:9092"
    links:
      - zookeeper

  zookeeper:
    image: wurstmeister/zookeeper:latest
    container_name: my-zookeeper-container
    ports:
      - "2181:2181"

  fastapi:
    build:
      context: ./fastapi-app
    container_name: my-fastapi-container
    environment:
      DATABASE_URL: postgresql://myuser:mypassword@postgres:5432/mydatabase
      KAFKA_BROKER: kafka:9092
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - kafka


