version: '3'
services:
  producer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: producer
    ports:
      - "8444:8444"
    environment:
      - KAFKA_REST_BOOTSTRAP_SERVERS=broker:29092

networks:
  default:
    external:
      name: master_default
