version: "3"
services:
  producer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: producer
    ports:
      - "8444:8444"
    environment:
      - KAFKA_REST_BOOTSTRAP_SERVERS=broker:9092
    networks:
      - master_wdw-net

networks:
  master_wdw-net:
    external: true